### ISSUE TITLE
Turtlesimのオブジェクトの形が書籍 図4-14と異なる

### ISSUE THREAD

**Issue by kanpapa** [NakanishiLabSFC/unity-ros2-robot-programming#2]
第４章で作成したTurtlesimオブジェクトですが、書籍記載のInspectorの値にするとHeadとBodyが離れて表示され、図4-14と異なります。HeadとBodyのPosition、Scaleの値は正しいでしょうか。
![image](https://github.com/NakanishiLabSFC/unity-ros2-robot-programming/assets/3832390/0e20111b-daf9-40e5-abe8-673b36404a38)

**Comment by te260ku** [comment]
ご指摘ありがとうございます。こちらでも同様の問題が生じることを確認しました。
書籍に記載されているHeadとBodyのPositionおよびScaleは正しいですが、p.100の手順⑥の表記に誤りがありました。
「Turtlesim」オブジェクトを右クリックして、とありますが、正しくは「Body」オブジェクトを右クリックして、です。正誤表にも追記しておきました。
今後も本書を読み進めるうえで不都合などあればお知らせください。

**Comment by kanpapa** [comment]
ご確認ありがとうございます。ご連絡いただいた手順で実施したところ正しい表示になりました。
引き続き熟読して進めます。ありがとうございました。
![image](https://github.com/NakanishiLabSFC/unity-ros2-robot-programming/assets/3832390/a7226535-f0f9-4243-a158-56c0402ab4d1)
